// src/components/UpdateContatoForm.vue
<script lang="ts" setup>
import type { Contato } from '@/types/Contato';
import tiposContato from '@/utils/tiposContato';
import AppButton from './AppButton.vue';
import AppLabel from './AppLabel.vue';
import AppInput from './AppInput.vue';
import AppSelect from './AppSelect.vue';
import { ref } from 'vue';

interface Props {
  contato: Contato;
}

const props = defineProps<Props>();

const data = ref<Contato>(props.contato);

const emit = defineEmits(['salvar', 'excluir', 'cancelar']);

function handleSalvarEmit(e: Event) {
  e.preventDefault();
  emit('salvar', data.value.id, data.value);
}

function handleExcluirEmit(e: Event) {
  e.preventDefault();
  emit('excluir', data.value.id);
}

function handleCancelarEmit(e: Event) {
  e.preventDefault();
  emit('cancelar');
}
</script>

<template>
  <form
    class="form"
    @submit="handleSalvarEmit"
  >
    <header class="form-header">
      <h3 class="form-heading">Detalhes do Contato</h3>
      <AppButton @click="handleCancelarEmit" variant="transparent" isSquare>
        X
      </AppButton>
    </header>
    <div class="form-row">
      <div class="form-field">
        <AppLabel htmlFor="nome">ID Cliente</AppLabel>
        <AppInput v-model="data.clienteId" id="nome" required />
      </div>
    </div>
    <div class="form-row">
      <div class="form-field">
        <AppLabel htmlFor="cpf">Tipo</AppLabel>
        <AppSelect
          v-model="data.tipo"
          :options="[...tiposContato]"
          id="tipo"
          required
        />
      </div>
      <div class="form-field">
        <AppLabel htmlFor="data-nascimento">Valor</AppLabel>
        <AppInput
          v-model="data.valor"
          id="data-nascimento"
          required
        />
      </div>
    </div>
    <div class="form-row">
      <div class="form-field">
        <AppLabel htmlFor="endereco">Observação</AppLabel>
        <AppInput v-model="data.observacao" id="endereco" />
      </div>
    </div>
    <div class="form-actions">
      <AppButton
        @click="handleExcluirEmit"
        variant="delete small"
        type="button"
      >
        Excluir
      </AppButton>
      <AppButton variant="add small" type="submit"> Salvar </AppButton>
    </div>
  </form>
</template>

// src/components/UpdateContatoForm/UpdateContatoForm.tsx
import { useState, useEffect, ChangeEvent } from 'react';
import { X } from 'react-feather';

import tiposContato from '../../utils/tiposContato';
import Select from '../Select/Select';
import Button from '../Button/Button';
import Label from '../Label/Label';
import Input from '../Input/Input';
import { Contato, ContatoPayload } from '../../types/contato';
import { ID } from '../../types/id';

type UpdateContatoFormProps = {
  contato: Contato;
  onSave: (id: ID, data: ContatoPayload) => void;
  onDelete: (id: ID) => void;
  onClose: () => void;
}

function UpdateContatoForm({ contato, onSave, onDelete, onClose }: Readonly<UpdateContatoFormProps> ) {
  const [data, setData] = useState<Contato>({ ...contato });

  useEffect(() => {
    if (contato) setData({ ...contato });
  }, [contato]);

  function handleOnChange(e: ChangeEvent<HTMLSelectElement | HTMLInputElement>, key: string) {
    const newValue = e.target.value;
    setData({ ...data, [key]: newValue });
  }

  return (
    <div className="modal-container" onClick={onClose}>
      <form
        onSubmit={(e) => {
          e.preventDefault();
          onSave(data.id, data);
        }}
        onClick={(e) => e.stopPropagation()}
        className="form"
      >
        <header className="form-header">
          <h3 className="form-heading">Detalhes do Contato</h3>
          <Button variant="transparent" onClick={onClose} isSquare>
            <X />
          </Button>
        </header>
        <div className="form-row">
          <div className="form-field">
            <Label htmlFor="clienteId">ID Cliente</Label>
            <Input
              onChange={(e) => handleOnChange(e, 'clienteId')}
              value={data.clienteId as string}
              id="clienteId"
              required
            />
          </div>
          <div className="form-field">
            <Label htmlFor="tipo">Tipo</Label>
            <Select
              onChange={(e) => handleOnChange(e, 'tipo')}
              options={[...tiposContato]}
              value={data.tipo}
              id="tipo"
              required
            />
          </div>
        </div>
        <div className="form-row">
          <div className="form-field">
            <Label htmlFor="valor">Valor</Label>
            <Input
              onChange={(e) => handleOnChange(e, 'valor')}
              value={data.valor}
              id="valor"
              required
            />
          </div>
        </div>
        <div className="form-row">
          <div className="form-field">
            <Label htmlFor="observacao">Observação</Label>
            <Input
              onChange={(e) => handleOnChange(e, 'observacao')}
              value={data.observacao}
              id="observacao"
            />
          </div>
        </div>
        <div className="form-actions">
          <Button
            onClick={() => onDelete(data.id)}
            variant="delete small"
            type="button"
          >
            Excluir
          </Button>
          <Button variant="add small" type="submit">
            Salvar
          </Button>
        </div>
      </form>
    </div>
  );
}

export default UpdateContatoForm;
