// src/components/AddContatoForm/AddContatoForm.jsx
import { X } from 'react-feather';
import { useState } from 'react';

import tiposContato from '../../utils/tiposContato';
import Select from '../Select/Select';
import Button from '../Button/Button';
import Label from '../Label/Label';
import Input from '../Input/Input';

function AddContatoForm({ onSave, onClose }) {
  const [data, setData] = useState({
    tipo: '',
    clienteId: '',
    valor: '',
    observacao: '',
  });

  function handleOnChange(e, key) {
    const newValue = e.target.value;
    setData({ ...data, [key]: newValue });
  }

  function handleSubmit(e) {
    e.preventDefault();
    onSave(data);
  }

  return (
    <div className="modal-container" onClick={onClose}>
      <form
        onClick={(e) => e.stopPropagation()}
        onSubmit={handleSubmit}
        className="form"
      >
        <header className="form-header">
          <h3 className="form-heading">Novo Contato</h3>
          <Button variant="transparent" onClick={onClose} isSquare>
            <X />
          </Button>
        </header>
        <div className="form-row">
          <div className="form-field">
            <Label htmlFor="clienteId">ID Cliente</Label>
            <Input
              onChange={(e) => handleOnChange(e, 'clienteId')}
              value={data.clienteId}
              id="clienteId"
              required
            />
          </div>
          <div className="form-field">
            <Label htmlFor="tipo">Tipo</Label>
            <Select
              onChange={(e) => handleOnChange(e, 'tipo')}
              options={tiposContato}
              value={data.tipo}
              id="tipo"
              required
            />
          </div>
        </div>
        <div className="form-row">
          <div className="form-field">
            <Label htmlFor="valor">Valor</Label>
            <Input
              onChange={(e) => handleOnChange(e, 'valor')}
              value={data.valor}
              id="valor"
              required
            />
          </div>
        </div>
        <div className="form-row">
          <div className="form-field">
            <Label htmlFor="observacao">Observação</Label>
            <Input
              onChange={(e) => handleOnChange(e, 'observacao')}
              value={data.observacao}
              id="observacao"
            />
          </div>
        </div>
        <div className="form-actions">
          <Button onClick={onClose} variant="delete">
            Cancelar
          </Button>
          <Button variant="add" type="submit">
            Salvar
          </Button>
        </div>
      </form>
    </div>
  );
}

export default AddContatoForm;

// src/components/AddContatoForm.vue
<script lang="ts" setup>
import AppButton from './AppButton.vue';
import AppLabel from './AppLabel.vue';
import AppInput from './AppInput.vue';
import AppSelect from './AppSelect.vue';
import FormRowLegend from './FormRowLegend.vue';
import tiposContato from '@/utils/tiposContato';
import { ref } from 'vue';
import type { ContatoPayload } from '@/types/Contato';

const contatoInitialData: ContatoPayload = {
  clienteId: '',
  tipo: 'Telefone',
  valor: '',
  observacao: '',
};

const data = ref<ContatoPayload>({ ...contatoInitialData });
const emit = defineEmits(['salvar', 'cancelar']);

function handleSalvarEmit(e: Event) {
  e.preventDefault();
  emit('salvar', data.value);
}

function handleCancelarEmit(e: Event) {
  e.preventDefault();
  emit('cancelar');
}
</script>

<template>
  <form
    class="form"
    @submit="handleSalvarEmit"
  >
    <header class="form-header">
      <h3 class="form-heading">Novo Cliente</h3>
      <AppButton @click="handleCancelarEmit" variant="transparent" isSquare>
        X
      </AppButton>
    </header>
    <FormRowLegend>Dados Pessoais</FormRowLegend>
    <div class="form-row">
      <div class="form-field">
        <AppLabel htmlFor="nome">ID Cliente</AppLabel>
        <AppInput v-model="data.clienteId" id="nome" required />
      </div>
    </div>
    <div class="form-row">
      <div class="form-field">
        <AppLabel htmlFor="cpf">Tipo</AppLabel>
        <AppSelect
          v-model="data.tipo"
          :options="[...tiposContato]"
          id="tipo"
          required
        />
      </div>
      <div class="form-field">
        <AppLabel htmlFor="data-nascimento">Valor</AppLabel>
        <AppInput
          v-model="data.valor"
          id="data-nascimento"
          required
        />
      </div>
    </div>
    <div class="form-row">
      <div class="form-field">
        <AppLabel htmlFor="endereco">Observação</AppLabel>
        <AppInput v-model="data.observacao" id="endereco" />
      </div>
    </div>
    <div class="form-actions">
      <AppButton @click="handleCancelarEmit" variant="delete">
        Cancelar
      </AppButton>
      <AppButton variant="add" type="submit"> Salvar </AppButton>
    </div>
  </form>
</template>
